<?php include __DIR__ . '/includes/header.phtml'; ?>

    <div class="container padding-top subheader"></div>

    <div class="container padding-top">
      <h2 class="error"><?=$title; ?></h2>
      <p>Sorry, that page was not found.</p>
      <hr class="featurette-divider">
    </div>

    <div class="container marketing">

<?php include __DIR__ . '/includes/company.phtml'; ?>

    </div> <!-- /container -->

<?php include __DIR__ . '/includes/footer.phtml'; ?>