<?php include __DIR__ . '/includes/header.phtml'; ?>

    <div class="container padding-top subheader"></div>

    <div class="container padding-top">
      <h2><?=$title; ?></h2>
<?php if (isset($content)): ?>
<?=$content; ?>
<?php endif; ?>

      <hr class="featurette-divider">
    </div>

    <div class="container marketing">

<?php include __DIR__ . '/includes/company.phtml'; ?>

    </div> <!-- /container -->

<?php include __DIR__ . '/includes/footer.phtml'; ?>